import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/common/Navbar";
import { WalletProvider } from "@solana/wallet-adapter-react";
import { CustomWalletProvider } from "@/providers/CustomWalletProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <CustomWalletProvider>
          <div className="flex flex-col justify-start min-h-screen w-full">
            <Navbar />
            <div className="flex-grow ">{children}</div>
          </div>
        </CustomWalletProvider>
      </body>
    </html>
  );
}
